apiVersion: v1
kind: Secret
metadata:
  name: edutoon-runtime
  namespace: edutoon-benchmark
type: Opaque
stringData:
  DB_PASS: ${DB_PASS}
  DB_ROOT_PASS: ${DB_ROOT_PASS}
  JWT_SECRET: ${JWT_SECRET}
  GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: edutoon-benchmark-account
  namespace: edutoon-benchmark
type: Opaque
stringData:
  BENCHMARK_EMAIL: ${BENCHMARK_EMAIL}
  BENCHMARK_PASSWORD: ${BENCHMARK_PASSWORD}
