apiVersion: v1
kind: ConfigMap
metadata:
  name: edutoon-config
  namespace: edutoon-benchmark
data:
  PORT: "3000"
  DB_HOST: edutoon-postgres
  DB_PORT: "5432"
  DB_USER: edutoon
  DB_NAME: edutoon_benchmark
  JWT_EXPIRES_IN: 1h
  FRONTEND_URL: http://edutoon-frontend:3333
  BACKEND_INTERNAL_URL: http://edutoon-backend:3000
  ALLOW_BENCHMARK_SEED: "true"
