apiVersion: v1
kind: ConfigMap
metadata:
  name: edutoon-grafana-provisioning
  namespace: edutoon-benchmark
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://edutoon-prometheus:9090
        isDefault: true
        editable: false
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: EduToon
        orgId: 1
        folder: EduToon
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards
